### ISSUE TITLE
MiniProfiler storage failure: undefined method `upcase' for [:exists, "MPRedisStoreha3b3tlmb7rm5r8zcf3a"]:Array

### ISSUE THREAD

**Issue by diegonulinga** [MiniProfiler/rack-mini-profiler#513] opened 2021-12-17 01:42 UTC
I moved from a single server to k8s, I changed the storage to redis and now I can't see the widget in production and that is the log that I have. 
I tested in my local with redis and works well

Redis version: 6.0.9
Rack mini profiler version: 2.2.1

If you need another information, just ask.
Thanks.

**Comment by jclusso** [comment] 2022-07-08 02:37
@diegonulinga did you ever figure out your issue?

**Comment by jclusso** [comment] 2022-07-08 04:22
It appears that disabling the [elastic-apm](https://github.com/elastic/apm-agent-ruby) gem resolves this. This isn't really a solution, but I'm not sure if the problem is in this or in that. @SamSaffron any ideas?

**Comment by diegonulinga** [comment] 2022-07-08 14:20
> @diegonulinga did you ever figure out your issue?

i couldn't make it work

**Comment by jclusso** [comment] 2022-07-08 16:59
@diegonulinga were you using elastic-apm?

**Comment by diegonulinga** [comment] 2022-07-08 17:08
yes, i am using it!

**Comment by jclusso** [comment] 2022-07-08 17:09
Well my PR linked above fixes it.

**Comment by nateberkopec** [comment] 2023-04-07 01:33
Fixed on the elastic-apm side.

**Closed by nateberkopec** 2023-04-07 01:33 UTC
