### ISSUE TITLE
Mini Profiler UI not displayed when the response is JSON

### ISSUE THREAD

**Issue by cireficc** [MiniProfiler/rack-mini-profiler#243] opened 2016-05-17 01:56 UTC
In a Rails JSON API, the profiler UI is not displayed, which is unfortunate!

[A workaround is easy though](http://stackoverflow.com/a/26801183/1986871); you need two tabs open - one for the JSON, one for the profiler. The second tab needs to be any page that renders HTML (for example the root route `/`). Make the JSON request, then refresh the page that renders HTML, and the profiler UI will show the JSON request.

Can this be fixed so that the profiler UI shows up on JSON-only pages, or is this by design (and why)?

**Comment by seanlinsley** [comment] 2016-06-04 19:14
It's impossible for the profiler to show up on JSON requests, because the browser only expects JSON. For HTML requests, we insert JS to render the profiler.

The only way to get around that is by making rack-mini-profiler a browser extension, but that's a huge amount of work.

**Comment by kbrock** [comment] 2016-06-06 03:51
The request is to actively push events to the browsers.

The infrastructure is not in place for this. It seems websockets /server sent events is overkill here.

Maybe when chrome adds adds header cookies for performance data this may become more viable

**Comment by SamSaffron** [comment] 2016-06-08 01:40
A custom page that does a req say every 5-10 seconds to update the list should do the trick without enormous amounts of added complexity. Alternatively you could use message bus on such a page. 

Totally support shipping a sample or even a custom page for dealing with this.

**Comment by southwolf** [comment] 2016-09-25 12:29
The profiler UI will not show up on /404.html in production environment for a rails-api project.

The `Rack::MiniProfiler.authorize_request` configuration won't help

Repo: https://github.com/southwolf/rack-profiler-in-production

**Comment by kbrock** [comment] 2016-09-26 13:37
Thanks @southwolf could you create a PR for your issue? This seems like a separate thread.

**Comment by oyeanuj** [comment] 2018-07-25 03:39
@SamSaffron or others around, what is the recommended way of using rack-mini-profiler with Rails in API only mode?

**Comment by benterprise** [comment] 2018-10-04 21:31
Also have an API only app that I'd like to monitor

**Comment by printercu** [comment] 2019-01-16 10:16
Maybe it's possible to add new `?pp=` flag which will suppress application output and render profiler layout for that request?

**Comment by SamSaffron** [comment] 2019-01-17 05:08
@oyeanuj / @printercu  the workaround is in the OP use two browser windows, one open to an HTML page. 

I think we should ship a blank page people can just hit so you can do `http://myapp.com/rack-mini-profiler/requests` or something to see everything. Then you don't have to roll out your own blank page.

**Comment by RudyOnRails** [comment] 2019-03-29 02:38
How is the profile info sent back to the browser normally? Is there some way to just update the DOM with JSON request profiles as they arrive? Reason I ask is because JSON requests that are mounted in Vue components get profiled just fine as part of the main page load profile I think. Seems like it would't be too difficult to include new subsequent AJAX requests, but I'm not sure how MP works and wouldn't know where to start.

**Comment by x-ji** [comment] 2019-05-27 13:33
I added an empty page to my API-only project, but the page doesn't seem to load any resource from `rack-mini-profiler` (i.e. doesn't make any requests to anything under `http://localhost:3000/mini-profiler-resources/`). I wonder if it has something to do with the `config.api_only = true` part in `application.rb`.

**Comment by x-ji** [comment] 2019-05-27 14:04
Never mind. I think I finally made it work. I just added a completely empty controller action, and left a corresponding template file under `app/views/`. The template file got rendered automatically and mini profiler showed up.

**Comment by x-ji** [comment] 2019-05-27 14:29
So it does look like I had to change `ApplicationController` to inherit from `ActionController::Base` to make it work, while I didn't need to do so in a vanilla app initialized with `rails new api_name --api`. I'm not sure why. Might be something related to Rails version or the configuration of that particular project.

**Comment by rinkei** [comment] 2019-10-09 05:47
I'm trying to update #396, but I got a trouble.
After getting `/rack-mini-profiler/requests`, my puma shows bellow logs.
```
Started GET "/rack-mini-profiler/requests" for 127.0.0.1 at 2019-10-08 12:53:16 +0900
ActionController::RoutingError (No route matches [GET] "/rack-mini-profiler/requests"):
```
Then puma don't receive any commands and other requests vanish.
Do you have any idea to debug this problem?

**Comment by jvalenciag** [comment] 2019-11-12 15:57
I'm having the same problem, does somebody have any clue of how to fix this?

> I'm trying to update #396, but I got a trouble.
> After getting `/rack-mini-profiler/requests`, my puma shows bellow logs.
> 
> ```
> Started GET "/rack-mini-profiler/requests" for 127.0.0.1 at 2019-10-08 12:53:16 +0900
> ActionController::RoutingError (No route matches [GET] "/rack-mini-profiler/requests"):
> ```
> 
> Then puma don't receive any commands and other requests vanish.
> Do you have any idea to debug this problem?

**Comment by SamSaffron** [comment] 2019-11-12 21:50
@OsamaSayegh  can you test this out? I would like to make sure `/requests` route works it makes it practical to debug json only sites.

**Comment by OsamaSayegh** [comment] 2020-07-05 12:18
Looks like I missed this one, sorry!

I tested `/rack-mini-profiler/requests` on my local Discourse instance and it seemed to work. Here is how I tested it:

* I opened a new tab and went to `/rack-mini-profiler/requests` and I saw MP speed badge to the left
* Opened another tab and loaded a `.json` route
* Went back to my MP tab, refreshed the page and it showed me a speed badge for the `.json` route (along with badges for other things like service worker) and I could see db queries etc.

Is there something I missed here? I was not aware of this little feature so I'm not familiar with how it's supposed to work.

**Comment by OsamaSayegh** [comment] 2020-07-13 20:34
@rinkei @jvalenciag I was able to reproduce this "error" you got but I don't think it's a legit error. If you go to `/rack-mini-profiler/requests` and see Mini Profiler speed badge on the page, then it is working as expected. Though I've opened https://github.com/MiniProfiler/rack-mini-profiler/pull/453 to make the error go away.

**Comment by OsamaSayegh** [comment] 2020-07-14 07:00
PR merged, closing this issue.

**Closed by OsamaSayegh** 2020-07-14 07:00 UTC

**Comment by benoittgt** [comment] 2024-01-25 09:53
Hello
I was thinking. It will be nice to have `?pp=request` that print the output directly? I didn't look at the code yet but I think it could be even better than having a page with the list of recent request?
