### ISSUE TITLE
Breaks apps which use require.js to load jquery

### ISSUE THREAD

**Issue by purcell** [MiniProfiler/rack-mini-profiler#77] opened 2014-05-02 10:24 UTC
`rack-mini-profiler` presumably loads jquery directly for its own use, but if the rest of the app uses `require.js` to load `jquery` as an AMD module, the module does not get defined properly. I guess that jquery detects that it is already loaded.

Not sure what a workaround would be, other than cutting out the `jquery` dependency from `rack-mini-profiler`, but perhaps it would at least be worthwhile cautioning `require.js` users.

**Comment by reustmd** [comment] 2015-12-22 17:47
@purcell @yoda I realize this is old, but I was wondering if anything else happened with this?

**Comment by purcell** [comment] 2015-12-22 18:28
@reustmd Unsure, sorry - I just stopped using `rack-mini-profiler`.

**Comment by reustmd** [comment] 2015-12-22 18:31
@purcell no worries. Do you use another tool instead?

**Comment by purcell** [comment] 2015-12-22 18:32
Not a similar tool, but I use NewRelic's development mode when I'm actively profiling site performance.

**Comment by rennhak** [comment] 2016-02-10 18:46
+1

**Comment by SamSaffron** [comment] 2016-03-06 12:25
I want to sort this out, but am going to need some help here, open to amending mp to detect requirejs and try to use it instead.

**Comment by yoda** [comment] 2016-03-06 13:21
I actually gave up on this we have moved to webpack instead with mixture of cjs and es6 import syntax. Miniprof seems to work in this environment.

**Comment by fuchse** [comment] 2016-11-28 18:12
+1

**Comment by MichaelSp** [comment] 2019-02-08 12:27
with the raise of https://github.com/rails/webpacker this really becomes a show stopper... Looks like I'm forced to live without this nice little gem 😭

**Comment by SamSaffron** [comment] 2019-02-10 22:23
I am open to cutting out jquery here. Maybe that is the best long term solution.

**Comment by jonathanhefner** [comment] 2019-11-03 19:17
This has been fixed by #399.

**Comment by SamSaffron** [comment] 2019-11-03 21:31
Confirmed as fixed, I love that we no longer have a jQuery dependency!

**Closed by SamSaffron** 2019-11-03 21:31 UTC
