### ISSUE TITLE
Windows 10 storage failure

### ISSUE THREAD

**Issue by ghost** [MiniProfiler/rack-mini-profiler#170] opened 2015-11-13 02:23 UTC
MiniProfiler storage failure: Invalid argument @ rb_sysopen for writing to file mp_views_::1

**Comment by jonathanhefner** [comment] 2019-11-02 19:14
This is a duplicate of #145, which has been fixed by #157.

**Comment by SamSaffron** [comment] 2019-11-03 21:38
confirmed as fixed, thanks @jonathanhefner

**Closed by SamSaffron** 2019-11-03 21:38 UTC
